import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"
import {
  Home,
  Package2,
  ShoppingCart,
} from "lucide-react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen w-full grid grid-cols-[280px_1fr]">
          {/* Left */}
          <div className="bg-muted/40 border-r">
            <div className="h-full max-h-screen flex flex-col gap-2">
              <div className="h-[60px] border-b p-4">
                <Link href="/" className="flex gap-2 font-semibold">
                  <Package2 className="h-6 w-6" />
                  <span className="">Vishaya AI</span>
                </Link>
              </div>
              <div className="flex-1">
                <nav className="grid items-start px-3 text-sm font-medium">
                  <Link href="/" className="flex items-center gap-3 rounded-lg px-2 py-2 text-muted-foreground transition-all hover:text-primary hover:bg-muted">
                    <Home className="h-4 w-4" />
                    Courses
                  </Link>
                  <Link href="/" className="flex items-center gap-3 rounded-lg px-2 py-2 text-muted-foreground transition-all hover:text-primary hover:bg-muted">
                    <ShoppingCart className="h-4 w-4" />
                    Settings
                  </Link>
                </nav>
              </div>
            </div>
          </div>
          {/* Right */}
          <div className="flex flex-col">
            <header className="h-[60px] border-b bg-muted/40">
            </header>
            <main className="flex flex-1 flex-col gap-4 p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
